apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: vote
        image: schoolofdevops/vote:v2
