apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: vote
        image:  cfathi/vote
        newTag: main-bdf10d3a-1751984897 # {"$imagepolicy":"flux-system:vote:tag"}
