apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
images:
  - name: cfathi/vote
    newTag: main-9ab5f410-1752159109 # {"$imagepolicy":"instavote:vote:tag"}
    #newTag: main-586dea36-1751985778 # {"$imagepolicy":"flux-system:vote"}

# images:
#   - name: schoolofdevops/vote # {"$imagepolicy":"flux-system:vote"}
#    # newTag: v3 # {"$imagepolicy":"flux-system:vote"}
