apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

images:
  - name: cfathi/vote
    newTag: main-bdf10d3a-1751984897 # {"$imagepolicy":"instavote:vote:tag"}

# images:
#   - name: schoolofdevops/vote # {"$imagepolicy":"flux-system:vote"}
#    # newTag: v3 # {"$imagepolicy":"flux-system:vote"}
