apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

images:
  - name: schoolofdevops/vote # {"$imagepolicy":"flux-system:vote"}
   # newTag: v3 # {"$imagepolicy":"flux-system:vote"}
