apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 1  
  template:    
    spec:
      containers:
      - image: schoolofdevops/vote:v1
        name: vote
